# Generated by Django 5.1.7 on 2025-03-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='categoria_id',
        ),
    ]
