# Generated by Django 5.1.7 on 2025-03-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_categoria_produto_categoria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
