# Generated by Django 5.1.7 on 2025-04-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
