# Generated by Django 5.1.7 on 2025-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tipo_desconto',
            field=models.CharField(default='Nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tipo_pagamento',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
    ]
