# Generated by Django 5.1.7 on 2025-04-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_relatorio_desconto_relatorio_tipo_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='nome_usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
