# Generated by Django 5.1.7 on 2025-03-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_mesa_id_pedido'),
        ('pedidos', '0001_initial'),
        ('produtos', '0002_alter_categoria_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
    ]
