# Generated by Django 5.1.7 on 2025-03-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0005_remove_mesa_id_pedido'),
        ('pedidos', '0002_rename_pedidos_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mesas.mesa'),
        ),
    ]
