# Generated by Django 5.1.7 on 2025-03-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='updated_at',
        ),
    ]
