# Generated by Django 5.1.7 on 2025-03-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_remove_mesa_created_at_remove_mesa_updated_at'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='id_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidos'),
        ),
    ]
