# Generated by Django 5.1.7 on 2025-03-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0004_alter_mesa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='id_pedido',
        ),
    ]
