# Generated by Django 5.1.7 on 2025-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0005_remove_mesa_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
